nodes: 1
gpus: 1
nr: 0
dataparallel: 0
workers: 8
dataset_dir: "./datasets"


seed: 42
batch_size: 128
image_size: 224
start_epoch: 0
epochs: 100
dataset: "mini-imagenet"
pretrain: True 

resnet: "resnet50"
projection_dim: 64

optimizer: "Adam"
weight_decay: 1.0e-6
temperature: 0.5


model_path: "checkpoint"
epoch_num: 100
reload: False

logistic_batch_size: 256
logistic_epochs: 1000
n_classes: 64