# fixed parapmeter
workers: 8
batch_size: 128
projection_dim: 64
optimizer: "Adam"
logistic_epochs: 50 
sample_epoch: 10
n_classes: 100
image_size: 224


# instance parapmeter
model_path: "..\\..\\moco-v3\\vit-b-300ep.pth.tar"
arch: "mocov3"   # simclr # resnet
encoder: "vit_base" #resnet50
dataset_name: "mini-imagenet"
way: 5
shot: 5