workers: 4
batch_size: 128
logistic_batch_size: 1
projection_dim: 64


optimizer: "Adam"
model_path: "..\\..\\moco-v3\\vit-b-300ep.pth.tar"
arch: "mocov3"   # simclr # resnet
encoder: "vit_base" #resnet50

logistic_epochs: 50
episode: 100 #  time of test

dataset_name: "mini-imagenet"
all_classes: 100
all_shot: 600
image_size: 224
n_classes: 5
shot: 5