# fixed parapmeter
optimizer: "Adam"
n_classes: 100
sample_per_class: 600
logistic_batch_size: 1
fn: "result"
desc: ""

# tricks
support_init_enabled: False

sample_epoch: 10
logistic_epochs: 1500
plot_sample_rate: 50 # sample 1 point per 50 points
way: 2

# entropy regularization
entropy_enabled: False
entropy_corr: 1.0e-8
# flolling settings are used only for trials
entropy_corr_epoch: 6