# fixed parapmeter
optimizer: "Adam"
logistic_epochs: 50
plot_sample_rate: 3 # sample 1 point per 3 points
n_classes: 100
sample_per_class: 600
sample_epoch: 1
logistic_batch_size: 1
fn: "result"
desc: ""

# tricks
support_init_enabled: True

# entropy regularization
entropy_enabled: True
entropy_corr_epoch: 5

