# fixed parapmeter
optimizer: "Adam"
n_classes: 100
sample_per_class: 600
logistic_batch_size: 1
fn: "result"
desc: ""

# tricks
support_init_enabled: True

sample_epoch: 10
logistic_epochs: 500
plot_sample_rate: 5 # sample 1 point per 50 points
way: 5
shot: 5